### ISSUE TITLE
malware

### ISSUE THREAD

**Issue by ghost** [ItziSpyder/ImproperUI#2]
https://github.com/ItziSpyder/ImproperUI/blob/main/src/main/java/io/github/itzispyder/improperui/util/StringUtils.java#L101

whats going on big guy

**Comment by ItziSpyder** [comment]
that is a function i forgot to remove from my other project

**Comment by ItziSpyder** [comment]
i copied this class over from my private discord webhooksender, you can see that the function isn't being called anywhere in the project

**Comment by ItziSpyder** [comment]
![image](https://github.com/ItziSpyder/ImproperUI/assets/114215797/0a680f42-0cd2-4622-a47a-a9815a88f79b)

**Comment by ItziSpyder** [comment]
people NEED to realize that discord webhooks AREN'T always malware, sure they are used for the wrong purposes in the hands of the wrong people, but that does NOT make it a malware

**Comment by ItziSpyder** [comment]
if this misunderstanding has been resolved @IssueDescription, please close this issue to prevent further misinformation to spread amongst the other users. i won't close it myself until you have read this message.

**Comment by Ceptea** [comment]
> https://github.com/ItziSpyder/ImproperUI/blob/main/src/main/java/io/github/itzispyder/improperui/util/StringUtils.java#L101
> 
> whats going on big guy

ahh yes malware. but the function isn't called at all.

**Comment by thetrouper** [comment]
I can vouch for Improper, I've decompiled their private "Coherent Client" multiple times, they have just reused the same utility class, if you were to check the usages, you would see that it has never been used in the codebase. [See no useages in this screenshot](https://epic.embed.fail/0totps4l.png). I can also prove that this wasn't intended for this mod, and instead, it was copy pasted from private client over to their public mod. Seen here, [decompiling the client shows the same classes reused](https://epic.embed.fail/pw6rysi9.png). Not only was the inclusion of these files an accident, but they didn't even end up being used ANYWHERE in the history of the mod. Code which formats a discord webhook was never executed on anyone's system as a result of ImproperIssues failure to notice the inclusion of a risky class from their client.
